# Generated by Django 2.2.16 on 2020-10-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="datatype",
            field=models.CharField(default="2011/01/Election", max_length=250),
        ),
    ]
