# Generated by Django 3.1.2 on 2020-10-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0004_auto_20170528_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='datatype',
            field=models.CharField(default='legacy/Election', max_length=250),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('election', 'Election'), ('referendum', 'Referendum')], default='election', max_length=250),
        ),
        migrations.AlterField(
            model_name='voterfile',
            name='voter_file',
            field=models.FileField(max_length=250, null=True, upload_to='voters/%Y/%m/%d'),
        ),
    ]
